title: Bandori Beatmap
description: Hi
template:
  repo: bandori-beatmap-template
  name: bandori-beatmap
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
